runtime: nodejs20

handlers:
  - url: /(.+\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf))$
    static_files: \1
    upload: (.+\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf))$
    secure: always

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always

env_variables:
  NODE_ENV: "production"
