steps:
  # Install dependencies with regular npm install instead of npm ci
  - name: "node:20"
    entrypoint: npm
    args: ["install", "--no-optional"]

  # Run our custom build script
  - name: "node:20"
    entrypoint: bash
    args: ["./build.sh"]
    env:
      - "NODE_OPTIONS=--max-old-space-size=4096"

  # Deploy to Firebase
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--only", "hosting"]

timeout: "1800s"
options:
  logging: CLOUD_LOGGING_ONLY
