steps:
  # Install dependencies
  - name: "node:20"
    entrypoint: npm
    args: ["ci"]

  # Build the Next.js application
  - name: "node:20"
    entrypoint: node
    args: ["build-firebase.js"]
    env:
      - "NODE_OPTIONS=--max-old-space-size=4096"

  # Deploy to Firebase
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--only", "hosting"]

timeout: "1800s"
options:
  logging: CLOUD_LOGGING_ONLY
