[build]
  command = "npm run build:improved"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  SKIP_FIREBASE_INIT = "true"
  SKIP_API_ROUTES = "true"
  SKIP_FIREBASE_ADMIN = "true"
  SKIP_FIREBASE_INIT_ON_BUILD = "true"
  REACT_EDITOR = "none"
  CHOKIDAR_USEPOLLING = "1"
  DEBUG_MODE = "true"
  NETLIFY = "true"
  NEXT_STATIC_EXPORT = "true"
  TYPESCRIPT_IGNORE_BUILD_ERRORS = "true"

[build.processing]
  skip_processing = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Next.js plugin not needed for static HTML builds
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.cloudfunctions.net; img-src 'self' data: https://*.googleapis.com; frame-src 'self' https://*.firebaseapp.com;"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add redirects for Firebase auth
[[redirects]]
  from = "/__/auth/*"
  to = "https://selah-reflect-app.firebaseapp.com/__/auth/:splat"
  status = 200

# Redirect API routes to fallback page since this is a static build
[[redirects]]
  from = "/api/*"
  to = "/fallback.html"
  status = 200

# Catch all redirects for non-existent pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Response = {NotFound = true}}