[build]
  command = "npm run build:netlify-fix"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  SKIP_FIREBASE_INIT_ON_BUILD = "true"
  SKIP_API_ROUTES = "true"
  SKIP_FIREBASE_ADMIN = "true"
  NETLIFY = "true"
  NEXT_PUBLIC_IS_NETLIFY_BUILD = "true"
  NEXT_STATIC_EXPORT = "false"

# Disable JavaScript bundling
[build.processing]
  skip_processing = true

[build.processing.js]
  bundle = false
  minify = false

# Ensure correct MIME types for all static assets
[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/firebase-fix.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/firebase-patch.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fix-node-modules.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(js|css|svg|jpg|jpeg|png|gif|ico|json)"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, immutable"

# Essential security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' *.netlify.app firebaseinstallations.googleapis.com firebasestorage.googleapis.com firestore.googleapis.com identitytoolkit.googleapis.com securetoken.googleapis.com; img-src 'self' data: blob: firebasestorage.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self'; connect-src 'self' *.netlify.app firebaseinstallations.googleapis.com firebasestorage.googleapis.com firestore.googleapis.com identitytoolkit.googleapis.com securetoken.googleapis.com; frame-src 'self';"
    
# Firebase auth redirects
[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/api/assetlinks"
  status = 200
  
# API route handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Use the Next.js plugin instead of redirecting everything to index.html
[plugin]
  package = "@netlify/plugin-nextjs"