# Google Cloud Buildpacks configuration
[[build.env]]
name = "NODE_OPTIONS"
value = "--max-old-space-size=4096"

[[build.env]]
name = "GOOGLE_SKIP_LOCKFILE_VALIDATION"
value = "true"

[[build.env]]
name = "NODE_ENV"
value = "production"

[[build.env]]
name = "SKIP_FIREBASE_INIT_ON_BUILD"
value = "true"

[[build.env]]
name = "SKIP_API_ROUTES"
value = "true"

[[build.env]]
name = "SKIP_FIREBASE_ADMIN"
value = "true"

[build]
command = "npm install && npm install --save-dev babel-loader @babel/core @babel/preset-env @babel/plugin-transform-private-methods @babel/plugin-transform-class-properties @babel/plugin-transform-private-property-in-object @babel/plugin-syntax-private-property-in-object && node patches/firebase-undici-fix/patch-undici-util.js && npm run build:firebase && cp -r out/* ."
