name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Node.js version
        run: node --version

      - name: List files for debugging
        run: ls -la

      - name: Apply Firebase fixes
        run: node fix-firebase-build.js

      - name: Check next.config.js
        run: cat next.config.js

      - name: Create output directory
        run: mkdir -p out

      - name: Create Firebase emulator file
        run: echo '{"hosting":{"public":"out"}}' > firebase.json.tmp

      - name: Run build script
        run: node build-firebase.js

      - name: List output directory
        run: ls -la out

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SELAH_REFLECT_APP }}"
          channelId: live
          projectId: selah-reflect-app
